# Generated by Django 3.2.6 on 2021-09-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='goals_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skills_description',
            new_name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
