# Generated by Django 3.2.6 on 2021-09-08 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='content',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='experience',
            new_name='projects',
        ),
        migrations.AddField(
            model_name='application',
            name='work_history',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
