# Generated by Django 3.2.6 on 2021-09-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_location_job_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
    ]
