# Generated by Django 3.2.7 on 2021-11-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20211021_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='changed_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
